"""Layer 7 v4.0 — tests for the 9-alert-types end-to-end validator.

Pins the contract of
``module6_evaluation/validate_nine_alert_types.py``:

  * The validator runs cleanly (every helper is wired and total).
  * Every AlertType is exercised; the report has 9 entries.
  * Every entry passes — i.e. the v4 helpers stay consistent across
    the four layers (Layer 3 triage, Layer 4 adapter, Layer 5 badge,
    Layer 6 routing).
  * The exclusivity invariants the validator asserts (purple badge,
    adversarial flag, L2_SECURITY_SPECIALIST routing) are baked into
    the report's per-type records.
  * The on-disk report under ``results/reports/`` is well-formed
    when present (skipped when not — the report is generated by
    running the validator script, not by importing it).
"""
from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from module6_evaluation.validate_nine_alert_types import run_validation
from src.data_models import AlertType


PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPORT_PATH = PROJECT_ROOT / "results" / "reports" / "nine_alert_types_validation.yaml"


# ── In-process validation ──────────────────────────────────────────────


@pytest.fixture(scope="module")
def report() -> dict:
    """Run the validator once per module and reuse the report."""
    return run_validation()


def test_report_is_well_formed(report: dict) -> None:
    assert report["format"] == "layer7_v4.nine_alert_types_validation"
    assert "summary" in report
    assert "per_type" in report
    assert "invariants_verified" in report
    assert isinstance(report["invariants_verified"], list)
    assert len(report["invariants_verified"]) >= 5


def test_summary_reports_all_nine_types(report: dict) -> None:
    summary = report["summary"]
    assert summary["total_alert_types"] == 9
    assert summary["passed"] + summary["failed"] == 9
    assert 0.0 <= summary["pass_rate"] <= 1.0


def test_overall_status_is_pass(report: dict) -> None:
    """The whole point of the validator is to be green — failures
    here mean an upstream v4 helper drifted out of contract."""
    assert report["summary"]["overall_status"] == "PASS", (
        f"validator FAILED: "
        f"{[e for e in report['per_type'] if e['status'] == 'FAIL']}"
    )


def test_every_alert_type_present_exactly_once(report: dict) -> None:
    types_in_report = [entry["alert_type"] for entry in report["per_type"]]
    assert sorted(types_in_report) == sorted(t.value for t in AlertType)
    assert len(set(types_in_report)) == 9


def test_every_entry_passed(report: dict) -> None:
    for entry in report["per_type"]:
        assert entry["status"] == "PASS", (
            f"{entry['alert_type']} failed: {entry['failures']}"
        )
        assert entry["failures"] == []


# ── Exclusivity invariants baked into the report ───────────────────────


def test_disagreement_anomaly_is_only_l2_security(report: dict) -> None:
    sec_types = [
        e["alert_type"] for e in report["per_type"]
        if e["layer6"]["recommended_tier"] == "L2_security_specialist"
    ]
    assert sec_types == ["DISAGREEMENT_ANOMALY"]


def test_disagreement_anomaly_is_only_adversarial(report: dict) -> None:
    adv_types = [
        e["alert_type"] for e in report["per_type"]
        if e["layer6"]["adversarial_flag"]
    ]
    assert adv_types == ["DISAGREEMENT_ANOMALY"]


def test_disagreement_anomaly_is_only_purple(report: dict) -> None:
    purple_types = [
        e["alert_type"] for e in report["per_type"]
        if e["layer5"]["badge"]["color"] == "#9333EA"
    ]
    assert purple_types == ["DISAGREEMENT_ANOMALY"]


def test_layer4_legacy_template_in_T1_to_T5(report: dict) -> None:
    """The adapter must always route to the legacy 5-template
    vocabulary so the existing rule-based generator can consume v4
    alert types."""
    valid = {"T1", "T2", "T3", "T4", "T5"}
    for entry in report["per_type"]:
        assert entry["layer4"]["legacy_template"] in valid, (
            f"{entry['alert_type']} → {entry['layer4']['legacy_template']}"
        )


def test_per_role_mitre_non_empty_for_every_type(report: dict) -> None:
    for entry in report["per_type"]:
        for role, text in entry["layer4"]["mitre_per_role"].items():
            assert text, f"{entry['alert_type']} role {role} MITRE empty"


def test_invariant_1_recorded_for_every_type(report: dict) -> None:
    """``c_detect ≥ p_xgb`` is the validator's check on the triage
    classifier; the recorded c_detect must be ≥ the input p_xgb."""
    for entry in report["per_type"]:
        triage = entry["triage"]
        assert triage["c_detect"] >= triage["input"]["p_xgb"] - 1e-9, (
            f"{entry['alert_type']}: c_detect={triage['c_detect']} "
            f"< p_xgb={triage['input']['p_xgb']}"
        )


# ── On-disk report (generated by running the script) ───────────────────


@pytest.mark.skipif(not REPORT_PATH.exists(), reason="report not generated yet")
def test_on_disk_report_parses_and_passes() -> None:
    """If the validator was run via ``python -m module6_evaluation.
    validate_nine_alert_types``, the on-disk YAML should match the
    in-process run's contract.
    """
    body = yaml.safe_load(REPORT_PATH.read_text())
    assert body["format"] == "layer7_v4.nine_alert_types_validation"
    assert body["summary"]["overall_status"] == "PASS"
    assert body["summary"]["total_alert_types"] == 9
