#!/usr/bin/env python3
"""Offline regeneration of Module 5's ``alert_responses.json``.

Used to verify Phase 1.2/1.3/1.4 (alert_id prefix, escalation
extensions, actions_metadata, MITRE plain_gloss) without re-executing
Modules 1-3. Loads:

  - risk_scores.npz                            (R, risk_levels, y_true)
  - test_phase1.parquet                        (attack_cats)
  - analyst_report.json + clinician_summaries.json
    (Phase 1.1 enrichment is preserved when those have already been
    regenerated by ``tools/phase1_regen_module4.py``)

…and calls ``build_all_records`` directly. Forces rule-based MVE
generation by unsetting LLM API keys for the duration of the run, so
the output is deterministic and doesn't depend on a live API key.

Writes ``results/reports/alert_responses.json`` in the envelope shape
``{_provenance, records}`` so the dashboard and the Phase-0 baseline
runner can consume it as-is.
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Force rule-based MVE for this run (no live API call).
os.environ.pop("OPENAI_API_KEY", None)
os.environ.pop("ANTHROPIC_API_KEY", None)

from common import split_paths as sp  # noqa: E402
from module5_responses.loaders import (  # noqa: E402
    load_attack_categories,
    load_explanations,
    load_risk_scores,
)
from module5_responses.pipeline import build_all_records  # noqa: E402

REPORTS_DIR = PROJECT_ROOT / "results" / "reports"


def main(split: str = "test") -> int:
    parquet     = sp.parquet(split)
    risk_npz    = sp.risk_scores(split)
    suffix      = sp.suffix(split)
    analyst_p   = REPORTS_DIR / f"analyst_report{suffix}.json"
    clinician_p = REPORTS_DIR / f"clinician_summaries{suffix}.json"

    print(f"[phase1-regen-m5] split={split}")
    for p, label in [(parquet, "parquet"), (risk_npz, "risk_npz"),
                     (analyst_p, "analyst"), (clinician_p, "clinician")]:
        if not p.exists():
            print(f"  MISSING: {label} → {p}", file=sys.stderr)
            return 2

    risk_data = load_risk_scores(risk_npz)
    analyst_by_idx, clinician_by_idx = load_explanations(analyst_p, clinician_p)
    attack_cats = load_attack_categories(parquet)

    print(f"[phase1-regen-m5] loaded {len(risk_data['R'])} samples, "
          f"{len(analyst_by_idx)} analyst alerts, "
          f"{len(clinician_by_idx)} clinician summaries")

    records, audit_trail = build_all_records(
        risk_data, attack_cats, analyst_by_idx, clinician_by_idx, parquet,
    )
    print(f"[phase1-regen-m5] generated {len(records)} alert records")

    # Phase 2 — inject counterfactual (under explanation.counterfactual)
    # and the counterfactual-derived try-first remediation hint
    # (under response.try_first_action) for every record whose
    # corresponding analyst entry has a feasible counterfactual.
    # Phase 4.1 — also inject stability (under explanation.stability)
    # so consumers see the band alongside counterfactual.
    n_cf_injected = 0
    n_stab_injected = 0
    for rec in records:
        idx = rec["sample_index"]
        analyst_entry = analyst_by_idx.get(idx)
        if not analyst_entry:
            continue
        cf = analyst_entry.get("counterfactual")
        if cf:
            rec.setdefault("explanation", {})["counterfactual"] = cf
            if cf.get("feasible") and cf.get("remediation_hint"):
                rec.setdefault("response", {})["try_first_action"] = cf["remediation_hint"]
            n_cf_injected += 1
        stab = analyst_entry.get("stability")
        if stab:
            rec.setdefault("explanation", {})["stability"] = stab
            n_stab_injected += 1
    print(f"[phase1-regen-m5] injected counterfactual into {n_cf_injected} records, "
          f"stability into {n_stab_injected} records")

    from common.artifact_versioning import ARTIFACT_VERSIONS
    envelope = {
        "_provenance": {
            "_schema_version": ARTIFACT_VERSIONS["alert_responses.json"],
            "split": split,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "module5_git_rev": _git_rev(),
            "n_input_samples": int(len(risk_data["R"])),
            "n_alerts_emitted": len(records),
            "n_normal_excluded": int(
                sum(1 for lv in risk_data["risk_levels"].tolist() if lv == "NORMAL")
            ),
            "filter_applied": "non_normal",
            "inputs": {},
        },
        "records": records,
    }
    out = REPORTS_DIR / f"alert_responses{suffix}.json"
    out.write_text(json.dumps(envelope, indent=2, default=str))
    print(f"[phase1-regen-m5] wrote {out.relative_to(PROJECT_ROOT)}")
    return 0


def _git_rev() -> str | None:
    import subprocess
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=PROJECT_ROOT, text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return None


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "test"))
