"""Render results/rq3_invariant_evidence.json into paper-ready markdown.

Output: results/rq3_invariant_evidence.md  (for thesis §5.6).
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = REPO_ROOT / "results" / "rq3_invariant_evidence.json"
OUT_MD = REPO_ROOT / "results" / "rq3_invariant_evidence.md"

_MARKER = {
    "pass": "PASS",
    "fail": "FAIL",
    "pending": "pending",
    "documented": "documented",
    "no_tests_found": "no-tests",
    "unknown": "unknown",
}


def main() -> None:
    if not JSON_PATH.exists():
        raise SystemExit(
            f"{JSON_PATH.relative_to(REPO_ROOT)} missing — "
            "run `python -m analysis.compile_invariant_evidence` first."
        )
    data = json.loads(JSON_PATH.read_text())

    lines: list[str] = []
    lines.append("# RQ3 - Architectural Invariant Evidence")
    lines.append("")
    lines.append(f"*Generated by `analysis/compile_invariant_evidence.py` "
                 f"on {data['_meta']['generated_at']}.*")
    lines.append(f"*Manifest: `{data['_meta'].get('manifest_path')}` "
                 f"(locked on "
                 f"{data['_meta'].get('taxonomy_locked_on', 'unknown')}).*")
    lines.append("")

    h = data["headline"]
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Overall:** {h['_overall_status']}")
    lines.append(f"- **Enforced (live tests):** {h['n_enforced']}/{h['n_invariants_total']}")
    lines.append(f"- **Pending (tests scheduled):** {h['n_pending']}/{h['n_invariants_total']}")
    lines.append(f"- **Documented (no test required):** {h['n_documented']}/{h['n_invariants_total']}")
    lines.append(f"- **Failed:** {h['n_failed']}/{h['n_invariants_total']}")
    if h.get("n_no_tests_found"):
        lines.append(f"- **No tests found:** {h['n_no_tests_found']}/{h['n_invariants_total']}")
    lines.append("")

    lines.append("## Invariant Status Table")
    lines.append("")
    lines.append("| # | Title | Severity | Serves RQ | Status | Verification |")
    lines.append("|---|---|---|---|---|---|")
    for inv in data["invariants"]:
        rqs = ", ".join(f"RQ{r}" for r in inv["serves_rqs"])
        lines.append(
            f"| {inv['id']} | {inv['title']} | {inv['severity']} | "
            f"{rqs} | "
            f"{_MARKER.get(inv['_overall_status'], inv['_overall_status'])} | "
            f"{inv.get('verification_method', '-')} |"
        )
    lines.append("")

    lines.append("## Per-Invariant Detail")
    lines.append("")
    for inv in data["invariants"]:
        lines.append(f"### Invariant {inv['id']} - {inv['title']}")
        lines.append("")
        lines.append(f"- **Severity:** {inv['severity']}")
        lines.append(f"- **Serves:** "
                     f"{', '.join(f'RQ{r}' for r in inv['serves_rqs'])}")
        lines.append(f"- **Status:** "
                     f"{_MARKER.get(inv['_overall_status'], inv['_overall_status'])}")
        lines.append(f"- **Verification:** "
                     f"{inv.get('verification_method', '-')}")
        lines.append("")

        tr = inv.get("test_results")
        if tr:
            lines.append(f"**Pytest results:** {tr['n_tests_passed']}/"
                         f"{tr['n_tests_total']} passed across "
                         f"{len(tr['test_files'])} file(s); "
                         f"{tr['n_tests_skipped']} skipped, "
                         f"{tr['n_tests_failed']} failed")
            for tf in tr["test_files"]:
                lines.append(f"  - `{tf}`")
            lines.append("")

        gr = inv.get("grep_results")
        if gr:
            lines.append(f"**Grep audit:** {gr['outcome']}")
            lines.append(f"  - target dirs: {gr['target_dirs']}")
            lines.append(f"  - forbidden pattern matches: "
                         f"{gr['n_pattern_matches']}")
            lines.append(f"  - forbidden import matches: "
                         f"{gr['n_import_matches']}")
            lines.append("")
            if gr["pattern_matches"][:3]:
                lines.append("  Sample matches:")
                for m in gr["pattern_matches"][:3]:
                    lines.append(f"    - `{m['pattern']}`: {m['match']}")
                lines.append("")

        if inv.get("_note"):
            lines.append(f"*Note: {inv['_note']}*")
            lines.append("")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_MD.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
