"""Render results/rq2_failure_mode_catalog.json into paper-ready markdown.

Output: results/rq2_failure_mode_catalog.md  (for thesis §5.3 + §7.2.3).
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CATALOG_JSON = REPO_ROOT / "results" / "rq2_failure_mode_catalog.json"
OUT_MD = REPO_ROOT / "results" / "rq2_failure_mode_catalog.md"


def main() -> None:
    if not CATALOG_JSON.exists():
        raise SystemExit(
            f"{CATALOG_JSON.relative_to(REPO_ROOT)} missing — "
            "run `python -m analysis.compile_failure_modes` first."
        )
    cat = json.loads(CATALOG_JSON.read_text())

    lines: list[str] = []
    lines.append("# RQ2 — Failure Mode Catalog")
    lines.append("")
    lines.append(f"*Generated by `analysis/compile_failure_modes.py` "
                 f"on {cat['_meta']['generated_at']}.*")
    lines.append("")
    lines.append(f"*Manifest: `{cat['_meta'].get('manifest_path')}` "
                 f"(taxonomy locked "
                 f"{cat['_meta'].get('taxonomy_locked_on', 'unknown')}).*")
    lines.append("")

    d = cat["_disclosure"]
    lines.append("## Disclosure")
    lines.append("")
    lines.append(f"- **Framing:** `{d['framing']}`")
    lines.append(f"- **Iteration performed:** {d['iteration_performed']}")
    lines.append(f"- **Evaluation rounds:** {d['evaluation_rounds']}")
    lines.append(f"- **Taxonomy predates data:** "
                 f"{d.get('taxonomy_predates_data')}")
    lines.append(f"- **Taxonomy source:** "
                 f"{d.get('taxonomy_source', 'unknown')}")
    lines.append(f"- **Intended use:** {d['intended_use']}")
    lines.append("")
    lines.append("> This catalog records observations. Per thesis Section "
                 "7.2.3, addressing the modes catalogued here is **future "
                 "work**, not a claim made in this thesis.")
    lines.append("")
    if cat["_meta"].get("_warning"):
        lines.append(f"> WARNING: {cat['_meta']['_warning']}")
        lines.append("")

    # ── Summary table ─────────────────────────────────────────
    lines.append("## 1. Summary — observations per category")
    lines.append("")
    lines.append("| Category | Observations | Impact metric (would affect if fixed) |")
    lines.append("|---|---:|---|")
    for cid, n in cat["summary"]["by_category"].items():
        impact = cat["catalog"][cid].get("impact_metric", "—")
        lines.append(f"| **{cid}** | {n} | {impact} |")
    total = cat["summary"]["total_observations"]
    lines.append(f"| **TOTAL** | **{total}** | |")
    lines.append("")

    other = cat["summary"]["other_bucket_diagnostic"]
    lines.append(
        f"**OTHER bucket diagnostic:** {other['size']} of {total} "
        f"observations ({other['size_pct']:.1%}) — {other['_assessment']}"
    )
    lines.append("")

    # ── Per-category detail ───────────────────────────────────
    lines.append("## 2. Per-category observations and recommended iteration")
    lines.append("")
    for cid, entry in cat["catalog"].items():
        lines.append(f"### {cid} — {entry['name']}")
        lines.append("")
        lines.append(f"**Description.** {entry['description'].strip()}")
        lines.append("")
        lines.append(f"**Observations:** {entry['n_observations']}  ")
        lines.append(f"**Status:** `{entry['_status']}`  ")
        lines.append(f"**Impact metric:** {entry.get('impact_metric', '—')}")
        lines.append("")
        lines.append("**Recommended iteration (future work):**")
        lines.append("")
        ri = (entry.get("recommended_iteration") or "").strip()
        for line in ri.splitlines() or [""]:
            lines.append(f"> {line}")
        lines.append("")

        if entry["evidence"]:
            lines.append("**Sample evidence:**")
            lines.append("")
            for ev in entry["evidence"][:5]:
                lines.append(f"- *{ev.get('source', '')}* — "
                             f"{ev.get('summary', '')}")
                excerpt = ev.get("excerpt") or ""
                if excerpt:
                    lines.append(f"  > {excerpt[:150]}")
            if entry["evidence_total_count"] > 5:
                lines.append(f"- *(+{entry['evidence_total_count'] - 5} "
                             "more in JSON catalog)*")
            lines.append("")
        else:
            lines.append("*No observations of this type collected.*")
            lines.append("")

    # ── Sources ───────────────────────────────────────────────
    lines.append("## 3. Sources")
    lines.append("")
    lines.append("**Sources used:**")
    lines.append("")
    for s in cat["_meta"]["sources_used"]:
        lines.append(f"- `{s}`")
    lines.append("")
    if cat["_meta"].get("sources_missing"):
        lines.append("**Sources missing (catalog incomplete):**")
        lines.append("")
        for s in cat["_meta"]["sources_missing"]:
            lines.append(f"- `{s}`")
        lines.append("")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_MD.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
